name: Western Digital DevOps Home Assignment CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CHUCK_API: https://api.chucknorris.io/jokes/random # We can set this at the repo level if we wish. this is more "as code" at the moment. 
  ENV_EXPORTER: CHUCK_API
    

jobs:
  Demo_CI:
    runs-on: arc-runner-set
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - run: pip install requests
      
      - name: Read Chuck Norris Joke
        id: read_cn_joke
        uses: ./.github/actions/read_cn_joke
        with:
          url: ${{ env.CHUCK_API }}
          
      - name: Return Pod Name
        id: get_pod_name
        uses: ./.github/actions/pod_exposer
        with:
          envexposer: ${{ env.ENV_EXPORTER }}
        
      - name: Workflow Summary
        env:
          CN_JOKE: "${{ steps.read_cn_joke.outputs.cn_joke }}"
          POD_NAME: "${{ steps.get_pod_name.outputs.pod_name }}"
        shell: bash
        run: echo "$CN_JOKE on $POD_NAME" >> $GITHUB_STEP_SUMMARY
